spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sdysjdsr1225*
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
#    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: request
    suffix: .ftl
  redis:
    host: localhost
    port: 6379

server:
  port: 8082
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/xuda/Downloads/sell.log
#  level:
#    com.qxholy.selltest.LoggerTest: debug

wechat:
  mpAppId: 
  mpAppSecret: 
  openAppId: 
  openAppSecret: 
  mchId: 
  mchKey: 
  keyPath: 
  notifyUrl: 

projectUrl:
  wechatMpAuthorize: 
  wechatOpenAuthorize: 
  bread: 
